
[env]
headers = [
    "library(dplyr)",
    "library(tidyr)"
]

[[type]]
name = "IntType"

[[type]]
name = "TableType"

[[type]]
name = "AggrType"

[[type]]
name = "ListType"
domain = ["[0]", "[1]", "[2]", "[0, 1]", "[1, 2]"]

[[type]]
name = "ColIndexType"
domain = ["0", "1", "2"]

[[type]]
name = "ConstType"
domain = ["0", "1", "2"]

[[type]]
name = "BoolFunctionType"
domain = [
    "!=", "==", ">", "<"
]

[[type]]
name = "NumFunctionType"
domain = [
    "/", "+", "-", "*"
]

[[api]]
name = "select"

    [api.return]
    type = "TableType"
    name = "ret"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "ListType"
    name = "param2"

    [[constraint]]
    type = "ValueCmp2"
    lhs = "param1.row"
    rhs = "ret.row" 
    operator = "=="

    [[constraint]]
    type = "ValueCmp2"
    lhs = param1.col
    rhs = "ret.col"
    operator = ">"

    [[constraint]]
    type = "ValueCmp2"
    lhs = "param1.col"
    rhs = "param2.max"
    operator = ">="

[[api]]
name = "group_by"

    [api.return]
    type = "TableType"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "ListType"
    name = "param2"

[[api]]
name = "inner_join"

    [api.return]
    type = "TableType"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "TableType"
    name = "param2"

[[api]]
name = "gather"

    [api.return]
    type = "TableType"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "ListType"
    name = "param2"


[[api]]
name = "spread"

    [api.return]
    type = "TableType"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "ColIndexType"
    name = "param2"

    [[api.param]]
    type = "ColIndexType"
    name = "param3"

[[api]]
name = "unite"

    [api.return]
    type = "TableType"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "ColIndexType"
    name = "param2"

    [[api.param]]
    type = "ColIndexType"
    name = "param3"

[[api]]
name = "summarise"

    [api.return]
    type = "TableType"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "AggrType"
    name = "param2"

    [[api.param]]
    type = "ColIndexType"
    name = "param3"

[[api]]
name = "separate"

    [api.return]
    type = "TableType"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "ColIndexType"
    name = "param2"

[[api]]
name = "filter"

    [api.return]
    type = "TableType"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "BoolFunctionType"
    name = "param2"

    [[api.param]]
    type = "ColIndexType"
    name = "param3"

    [[api.param]]
    type = "ConstType"
    name = "param4"


[[api]]
name = "mutate"

    [api.return]
    type = "TableType"

    [[api.param]]
    type = "TableType"
    name = "param1"

    [[api.param]]
    type = "NumFunctionType"
    name = "param2"

    [[api.param]]
    type = "ColIndexType"
    name = "param3"

    [[api.param]]
    type = "ColIndexType"
    name = "param4"

